name: WNBA Sheets-only Props + Projections

on:
  schedule:
    - cron: '17 13 * * *'   # ~9:17am ET daily (cron runs in UTC)
  workflow_dispatch:

jobs:
  sheets_only:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib pillow gspread google-auth gspread_dataframe scipy

      - name: Materialize service account JSON
        shell: bash
        run: |
          # Write the secret EXACTLY as-is into a file (no heredoc, avoids YAML parse issues)
          printf '%s' "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > sa.json

          # Quick sanity check
          python - <<'PY'
          import json
          j = json.load(open("sa.json"))
          assert "private_key" in j and j["private_key"].startswith("-----BEGIN PRIVATE KEY-----")
          print("OK: SA JSON parsed")
          PY

          # Let Google libs find it
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/sa.json" >> $GITHUB_ENV

      - name: Run sheets-only runner (export context)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          OUTPUT_DIR: ./out
        run: python sheets_only_runner.py

      - name: Run prop model (compute projections)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          OUTPUT_DIR: ./out
        run: python props_model.py

      - name: Push projections back to Sheet
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          OUTPUT_DIR: ./out
        run: python push_wnba_to_gsheets_v4.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wnba-props-projections
          path: out/**
